<?php
return [
    'sim_dep_tra_gop'=>[
        'price_from'=>20000000,
        'tra_gop'=>[
            'ky_han'=>[3,6,9,12], // month
            'tra_truoc'=>[30,40,50,60], // %
            'lai_suat'=>0.03,
        ]
    ],
    'cdn_sim_card'=> env('CDN_SIM_CARD','https://static.simthanglong.net'),
    'api_sim_url' => env('API_SIM_URL', ""),
    'topsim_base_api' => env('TOPSIM_BASE_API', ""),
    'tele_push_api' => env('TELE_PUSH_API', ""),
    'cdn_asset' => [
        "static.cdn.simthanglong.net" => "webp|jpg|jpeg|png|gif|svg|ico|css|js|eot|woff|ttf",
    ],
    'hung_cat_sim' => [
        0=>['diengiai'=>'Số phận cao nhất sẽ được thành công','ten'=>'Đại cát','catid'=>115],
        1=>['diengiai'=>'Đại triển hồng đồ, khả được thành công','ten'=>'Cát','catid'=>116],
        2=>['diengiai'=>'Thăng trầm không số, về già vô công','ten'=>'Bình','catid'=>117],
        3=>['diengiai'=>'Ngày ngày tiến tới, mọi vạn sự thuận toàn','ten'=>'Đại cát','catid'=>115],
        4=>['diengiai'=>'Tiền đồ gai gốc, đau khổ theo đuổi','ten'=>'Hung','catid'=>118],
        5=>['diengiai'=>'Làm ăn phát đạt, danh lợi đều có','ten'=>'Đại cát','catid'=>115],
        6=>['diengiai'=>'Trời cho số phận, có thể thành công','ten'=>'Cát','catid'=>116],
        7=>['diengiai'=>'Ôn hoà êm dịu, nhất phải thành công','ten'=>'Cát','catid'=>116],
        8=>['diengiai'=>'Qua đoạn gian nan, có ngày thành công','ten'=>'Cát','catid'=>116],
        9=>['diengiai'=>'Tự làm vô sức, thất bại khó lường','ten'=>'Hung','catid'=>118],
        10=>['diengiai'=>'Tâm sức làm không, không được đến bờ','ten'=>'Hung','catid'=>118],
        11=>['diengiai'=>'Vững đi từng bước, được người trọng vọng','ten'=>'Cát','catid'=>116],
        12=>['diengiai'=>'Gầy gò yếu đuối, mọi việc khó thành','ten'=>'Hung','catid'=>118],
        13=>['diengiai'=>'Trời cho cát vận, được người kính trọng','ten'=>'Đại cát','catid'=>115],
        14=>['diengiai'=>'Nữa được nữa bại, dựa vào nghị lực','ten'=>'Bình','catid'=>117],
        15=>['diengiai'=>'Đại sự thành tựu, nhất định hưng vượng','ten'=>'Cát','catid'=>116],
        16=>['diengiai'=>'Thành tựu to lớn, tên tuổi lừng danh','ten'=>'Đại cát','catid'=>115],
        17=>['diengiai'=>'Quý nhân trợ giúp, sẽ đạt thành công','ten'=>'Cát','catid'=>116],
        18=>['diengiai'=>'Thuận lợi xương thịnh, trăm việc trôi trải','ten'=>'Đại cát','catid'=>115],
        19=>['diengiai'=>'Nội ngoại bất hoà, khó khăn muôn phần','ten'=>'Hung','catid'=>118],
        20=>['diengiai'=>'Vượt mọi gian nan, lo xa nghĩ hoài','ten'=>'Đại hung','catid'=>119],
        21=>['diengiai'=>'Chuyên tâm kinh doanh, hay dùng trí tuệ','ten'=>'Cát','catid'=>116],
        22=>['diengiai'=>'Có tài không làm, việc không gặp may','ten'=>'Hung','catid'=>118],
        23=>['diengiai'=>'Tên tuổi bốn phương, sẽ thành đạt nghiệp','ten'=>'Đại cát','catid'=>115],
        24=>['diengiai'=>'Phải dựa tự lập, sẽ thành đại nghiệp','ten'=>'Đại cát','catid'=>115],
        25=>['diengiai'=>'Thiên thời địa lợi, vì được nhân cách','ten'=>'Đại cát','catid'=>115],
        26=>['diengiai'=>'Bão táp phong ba, qua mọi nguy hiểm','ten'=>'Hung','catid'=>118],
        27=>['diengiai'=>'Lúc thắng lúc thua, giữ được thành công','ten'=>'Cát','catid'=>116],
        28=>['diengiai'=>'Tiến mãi không lùi, trí tuệ được dùng','ten'=>'Đại cát','catid'=>115],
        29=>['diengiai'=>'Cát hung chia đôi, được chia mỗi nữa','ten'=>'Hung','catid'=>118],
        30=>['diengiai'=>'Danh lợi được mùa, đại sự thành công','ten'=>'Đại cát','catid'=>115],
        31=>['diengiai'=>'Con rồng trong nước, thành công sẽ đến','ten'=>'Đại cát','catid'=>115],
        32=>['diengiai'=>'Dùng chí lâu dài, sẽ được xương thịnh','ten'=>'Cát','catid'=>116],
        33=>['diengiai'=>'Rủi ro không ngừng, khó có thành công','ten'=>'Hung','catid'=>118],
        34=>['diengiai'=>'Số phận trung cát, tiến lùi bảo thủ','ten'=>'Bình','catid'=>117],
        35=>['diengiai'=>'Trôi nổi bập bùng, thường hay gặp nạn','ten'=>'Hung','catid'=>118],
        36=>['diengiai'=>'Tránh được điềm ác, thuận buồm xuôi gió','ten'=>'Cát','catid'=>116],
        37=>['diengiai'=>'Danh thì được tiếng, lợi thì bằng không','ten'=>'Bình','catid'=>117],
        38=>['diengiai'=>'Đường rộng thênh thang, nhìn thấy tương lai','ten'=>'Đại cát','catid'=>115],
        39=>['diengiai'=>'Lúc thịnh lúc suy, chìm nổi vô định','ten'=>'Bình','catid'=>117],
        40=>['diengiai'=>'Thiên ý cát vận, tiền đồ sáng sủa','ten'=>'Đại cát','catid'=>115],
        41=>['diengiai'=>'Sự nghiệp không chuyên, hầu như không thành','ten'=>'Hung','catid'=>118],
        42=>['diengiai'=>'Nhẫn nhịn chịu đựng, xấu cũng thành tốt','ten'=>'Cát','catid'=>116],
        43=>['diengiai'=>'Cây xanh trổ lá, đột nhiên thành công','ten'=>'Cát','catid'=>116],
        44=>['diengiai'=>'Ngược với ý mình, tham công lỡ việc','ten'=>'Hung','catid'=>118],
        45=>['diengiai'=>'Quanh co khúc khỉu, khó khăn kéo dài','ten'=>'Hung','catid'=>118],
        46=>['diengiai'=>'Quý nhân giúp trợ, thành công đại sự','ten'=>'Đại cát','catid'=>115],
        47=>['diengiai'=>'Danh lợi đều có, thành công đại sự','ten'=>'Đại cát','catid'=>115],
        48=>['diengiai'=>'Gặp cát được cát, gặp hung thì hung','ten'=>'Bình','catid'=>117],
        49=>['diengiai'=>'Hung cát cùng có, một thành một bại','ten'=>'Bình','catid'=>117],
        50=>['diengiai'=>'Một thịnh một suy, bồng bền sóng gió','ten'=>'Bình','catid'=>117],
        51=>['diengiai'=>'Trời quang mây tạnh, đạt được thành công','ten'=>'Cát','catid'=>116],
        52=>['diengiai'=>'Xương thịnh nửa số, cát trước hung sao','ten'=>'Hung','catid'=>118],
        53=>['diengiai'=>'Nỗ lực hết mình, thành công ít ỏi','ten'=>'Bình','catid'=>117],
        54=>['diengiai'=>'Bề ngoài tươi sáng, án hoạn sẽ tới','ten'=>'Hung','catid'=>118],
        55=>['diengiai'=>'Ngược lại ý mình, khó được thành công','ten'=>'Đại hung','catid'=>119],
        56=>['diengiai'=>'Nỗ lực phấn đấu, phận tốt quay về','ten'=>'Cát','catid'=>116],
        57=>['diengiai'=>'Bấp bên nhiều chuyện, hung trước cát sau','ten'=>'Bình','catid'=>117],
        58=>['diengiai'=>'Gặp việc do dự, khó có thành công','ten'=>'Hung','catid'=>118],
        59=>['diengiai'=>'Mơ mơ hồ hồ, khó định phương hướng','ten'=>'Bình','catid'=>117],
        60=>['diengiai'=>'Mây che nửa trăng, dấu hiệu phong ba','ten'=>'Hung','catid'=>118],
        61=>['diengiai'=>'Lo nghĩ nhiều điều, mọi việc không thành','ten'=>'Hung','catid'=>118],
        62=>['diengiai'=>'Biết hướng nỗ lực, con đường phồn vinh','ten'=>'Cát','catid'=>116],
        63=>['diengiai'=>'Mười việc chín không, mất công mất sức','ten'=>'Hung','catid'=>118],
        64=>['diengiai'=>'Cát vận tự đến, có được thành công','ten'=>'Cát','catid'=>116],
        65=>['diengiai'=>'Nội ngoại bất hoà, thiếu thốn tín nhiệm','ten'=>'Bình','catid'=>117],
        66=>['diengiai'=>'Mọi việc như ý , phú quý tự đến','ten'=>'Đại cát','catid'=>115],
        67=>['diengiai'=>'Nắm vững thời cơ , thành công sẽ đến','ten'=>'Cát','catid'=>116],
        68=>['diengiai'=>'Lo trước nghĩ sau, thường hay gặp nạn','ten'=>'Hung','catid'=>118],
        69=>['diengiai'=>'Bấp bênh kinh doanh, khó tránh vất vả','ten'=>'Hung','catid'=>118],
        70=>['diengiai'=>'Cát hung đều có, chỉ dựa chí khí','ten'=>'Bình','catid'=>117],
        71=>['diengiai'=>'Được rồi lại mất, khó có bình yên','ten'=>'Hung','catid'=>118],
        72=>['diengiai'=>'An lạc tự đến, tự nhiên cát tường','ten'=>'Cát','catid'=>116],
        73=>['diengiai'=>'Như là vô mưu, khó được thành đạt','ten'=>'Bình','catid'=>117],
        74=>['diengiai'=>'Trong lành có hung, tiến không bằng giữ','ten'=>'Bình','catid'=>117],
        75=>['diengiai'=>'Nhiều điều đại hung, hiện tượng phá sản','ten'=>'Đại hung','catid'=>119],
        76=>['diengiai'=>'Khổ trước sướng sau, không bị thất bại','ten'=>'Cát','catid'=>116],
        77=>['diengiai'=>'Nửa được nửa mất, sang mà không thực','ten'=>'Bình','catid'=>117],
        78=>['diengiai'=>'Tiền đồ tươi sáng, tràn đầy hy vọng','ten'=>'Đại cát','catid'=>115],
        79=>['diengiai'=>'Được rồi lại mất, lo cũng bằng không','ten'=>'Hung','catid'=>118]
    ]
];
