<?php
namespace App\Enums;

class SimType {
    public const FILTER_CATES = [
        [
            "label" => "4444",
            "title" => "Sim Tứ quý",
            "name" => "Sim Tứ quý",
            "c" => "68",
            "link" => "/sim-tu-quy",
            "showCat" => [],
            "notFilterItem" => ['types'],
            "show_mobile"=>true,
            "priceRange"=>[1900000,7837000000],
        ],
        [
            "label" => "55555",
            "name" => "Sim Ngũ quý",
            "title" => "Sim Ngũ quý",
            "c" => "99",
            "link" => "/sim-ngu-quy",
            "notFilterItem" => ['types'],
            "show_mobile"=>true,
            "priceRange"=>[22490000,5500000000],
        ],
        [
            "label" => "666.666",
            "title" => "Sim Lục quý",
            "name" => "Sim Lục quý",
            "c" => "100",
            "link" => "/sim-luc-quy",
            "notFilterItem" => ['types'],
            "show_mobile"=>true,
            "priceRange"=>[59990000,8900000000],
        ],
        [
            "name" => "333",
            "title" => "Sim Tam hoa",
            "label" => "333",
            "c" => "80",
            "link" => "/sim-tam-hoa",
            "notFilterItem" => ['types'],
            "show_mobile"=>true,
            "priceRange"=>[99000,2475000000],
        ],
        [
            "name" => "333.333",
            "title" => "Sim Tam hoa kép",
            "label" => "333",
            "c" => "102",
            "link" => "/sim-tam-hoa-kep",
            "notFilterItem" => ['types'],
            "show_mobile"=>false,
            "priceRange"=>[4780000,2475000000],
        ],
        [
            "label" => "199x",
            "name" => "Sim Năm sinh",
            "title" => "Sim Năm sinh",
            "c" => '77',
            "title_seo" => "Sim Năm sinh",
            "link" => "/sim-nam-sinh",
            "notFilterItem" => ['types'],
            "show_mobile"=>true,
            "priceRange"=>[220000,6571500000],
        ],
        [
            "label" => "68.68",
            "name" => "Sim Lộc phát",
            "title" => "Sim Lộc phát",
            "c" => '73',
            "link" => "/sim-loc-phat",
            "notFilterItem" => ['types'],
            "show_mobile"=>true,
            "priceRange"=>[99000,6739000000],
        ],
        [
            "label" => "39.79",
            "name" => "Sim Thần Tài",
            "title" => "Sim Thần Tài",
            "c" => '72',
            "link" => "/sim-than-tai",
            "notFilterItem" => ['types'],
            "show_mobile"=>false,
            "priceRange"=>[250000,6160000000],
        ],
        [
            "label" => "AABBCC",
            "title" => "Sim Dễ nhớ",
            "name" => "Sim Dễ nhớ",
            "c" => "76",
            "link" => "/sim-de-nho",
            "notFilterItem" => ['types'],
            "show_mobile"=>true,
            "priceRange"=>[110000,11265500000],
        ],
        [
            "label" => "xx",
            "name" => "Sim trả góp",
            "title" => "Sim trả góp",
            "c" => '200',
            "link" => "/sim-dep-tra-gop",
            "notFilterItem" => ['types'],
            "pr" => "20000000-10000000000000",
            "show_mobile"=>true,
            "priceRange"=>[10000000,7837000000],
        ],
        [
            "label" => "xx",
            "name" => "Sim giá rẻ",
            "title" => "Sim giá rẻ",
            "link" => "/sim-gia-re",
            "notFilterItem" => ['types'],
            "c" => "-1",
            "pr" => "0-3000000",
            "show_mobile"=>true,
            "priceRange"=>[99000,3000000],
        ],
        [
            "label" => "ABC.ABC",
            "title" => "Sim Taxi",
            "name" => "Sim Taxi",
            "c" => "74",
            "link" => "/sim-taxi",
            "notFilterItem" => ['types'],
            "showCat" => ["/sim-taxi-2", "/sim-taxi-3", "/sim-taxi-4"],
            "show_mobile"=>true,
            "priceRange"=>[499000,112600000000],
        ],
        [
            "label" => ".666666.",
            "title" => "Sim Lục quý giữa",
            "name" => "Sim Lục quý giữa",
            "c" => "105",
            "link" => "/sim-luc-quy-giua",
            "notFilterItem" => ['types'],
            "show_mobile"=>false,
            "priceRange"=>[6140000,7400000000],
        ],
        [
            "label" => ".55555.",
            "title" => "Sim Ngũ quý giữa",
            "name" => "Sim Ngũ quý giữa",
            "c" => "104",
            "link" => "/sim-ngu-quy-giua",
            "notFilterItem" => ['types'],
            "show_mobile"=>false,
            "priceRange"=>[599000,1416000000],
        ],
        [
            "label" => ".4444.",
            "title" => "Sim Tứ quý giữa",
            "name" => "Sim Tứ quý giữa",
            "c" => "103",
            "link" => "/sim-tu-quy-giua",
            "notFilterItem" => ['types'],
            "show_mobile"=>false,
            "priceRange"=>[300000,6697000000],
        ],
        [
            "label" => "VIP",
            "title" => "Sim VIP",
            "name" => "Sim VIP",
            "c" => "82",
            "link" => "/sim-vip",
            "notFilterItem" => ['types'],
            "show_mobile"=>false,
            "priceRange"=>[670000,15000000000],
        ],
        [
            "label" => "09x",
            "title" => "Sim đầu số cổ",
            "c" => "106",
            "query" => ["090*", "091*", "093*", "094*", "096*", "090*", "097*", "098*"],
            "link" => "/sim-dau-so-co",
            "notFilterItem" => ['types'],
            "show_mobile"=>false,
            "priceRange"=>[250000,7900000000],
        ],
        [
            "label" => "xx",
            "name" => "Sim khuyến mãi",
            "title" => "Sim khuyến mãi",
            "link" => "/sim-khuyen-mai",
            "notFilterItem" => ['types'],
            "c" => "-2",
            "s"=>'3829',
            "show_mobile"=>true,
            "priceRange"=>[499000,71250000],
        ],
        [
            "label" => "6789",
            "title" => "Sim Tiến lên",
            "name" => "Sim Tiến lên",
            "c" => "81",
            "link" => "/sim-tien-len",
            "notFilterItem" => ['types'],
            "showCat" => ["/sim-tien-3", "/sim-tien-4", "/sim-tien-5"],
            "show_mobile"=>false,
            "priceRange"=>[110000,15000000000],
        ],
        [
            "label" => "AA.BB",
            "title" => "Sim Lặp kép",
            "name" => "Sim Lặp kép",
            "c" => "67",
            "link" => "/sim-lap-kep",
            "notFilterItem" => ['types'],
            "showCat" => ["/sim-lap", "/sim-kep", "/sim-kep-2", "/sim-kep-3", "/sim-kep-4", "/sim-lap-2", "/sim-lap-3", "/sim-lap-4"],
            "show_mobile"=>false,
            "priceRange"=>[99000,112600000000],
        ],
        [
            "label" => "AB.BA",
            "title" => "Sim Gánh đảo",
            "name" => "Sim Gánh đảo",
            "c" => "79",
            "link" => "/sim-ganh-dao",
            "notFilterItem" => ['types'],
            "show_mobile"=>false,
            "priceRange"=>[250000,1785500000],
        ],
        [
            "label" => "75.78.78",
            "title" => "Sim Số độc",
            "name" => "Sim Số độc",
            "c" => "78",
            "notFilterItem" => ['types'],
            "link" => "/sim-so-doc",
            "show_mobile"=>false,
            "priceRange"=>[99000,15000000000],
        ],
        [
            "label" => "38.78",
            "name" => "Sim Ông Địa",
            "title" => "Sim Ông Địa",
            "c" => '70',
            "link" => "/sim-ong-dia",
            "notFilterItem" => ['types'],
            "show_mobile"=>false,
            "priceRange"=>[110000,1354500000],
        ],
        [
            "label" => "xx",
            "name" => "Sim trả sau",
            "title" => "Sim trả sau",
            "link" => "/sim-tra-sau",
            "notFilterItem" => ['types'],
            "c" => "-3",
            "s"=>'3829',
            "pr" => "0-3000000",
            "show_filter"=> false,
            "show_mobile"=>false,
            "priceRange"=>[499000,3000000],
        ],
        [
            "label" => "xx88",
            "name" => "Sim Đại Cát",
            "title" => "Sim Đại Cát",
            "c" => '115',
            "show_filter"=> false,
            "link" => "/sim-dai-cat",
            "notFilterItem" => ['types'],
            "show_mobile"=>false,
            "priceRange"=>[99000,6613500000],
        ],
        [
            "label" => "",
            "name" => "Sim phong thủy",
            "title" => "Sim phong thủy",
            "c" => '',
            "link" => "/sim-phong-thuy",
            "notFilterItem" => ['types'],
            "show_mobile"=>true,
            "show_filter"=>false
        ]
    ];
    public const FILTER_PRICES = [
        [
            "label"=>"< 500 nghìn",
            "name" => "Dưới 500 nghìn",
            "h1" => "Sim số đẹp giá dưới 500 nghìn",
            "title" => "Sim dưới 500 nghìn",
            "notFilterItem" => ['prices'],
            "link" => "/sim-duoi-500-nghin",
            "pr" => "0-500000",
            "show_mobile"=> true,
            "priceRange"=>[99000,500000],
        ],
        [
            "label" => "500K - 1 triệu",
            "name" => "500K - 1 triệu",
            "h1" => "Sim số đẹp giá 500K - 1 triệu",
            "title" => "Sim giá 500 - 1 triệu",
            "notFilterItem" => ['prices'],
            "link" => "/sim-500-nghin-den-1-trieu",
            "pr" => "500000-1000000",
            "show_mobile"=> true,
            "priceRange"=>[500000,1000000],
        ],
        [
            "label" => "1 - 3 triệu",
            "name" => "1 - 3 triệu",
            "h1" => "Sim số đẹp giá 1 - 3 triệu",
            "title" => "Sim giá 1 - 3 triệu",
            "notFilterItem" => ['prices'],
            "link" => "/sim-1-trieu-den-3-trieu",
            "pr" => "1000000-3000000",
            "show_mobile"=> true,
            "priceRange"=>[1000000,3000000],
        ],
        [
            "label" => "3 - 5 triệu",
            "name" => "3 - 5 triệu",
            "h1" => "Sim số đẹp giá 3 - 5 triệu",
            "title" => "Sim giá 3 - 5 triệu",
            "notFilterItem" => ['prices'],
            "link" => "/sim-3-trieu-den-5-trieu",
            "pr" => "3000000-5000000",
            "show_mobile"=> true,
            "priceRange"=>[3000000,5000000],
        ],
        [
            "label" => "5 - 10 triệu",
            "name" => "5 - 10 triệu",
            "h1" => "Sim số đẹp giá 5 - 10 triệu",
            "title" => "Sim giá 5 - 10 triệu",
            "notFilterItem" => ['prices'],
            "link" => "/sim-5-trieu-den-10-trieu",
            "pr" => "5000000-10000000",
            "show_mobile"=> true,
            "priceRange"=>[5000000,10000000],
        ],
        [
            "label" => "10 - 50 triệu",
            "name" => "10 - 50 triệu",
            "h1" => "Sim số đẹp giá 10 - 50 triệu",
            "title" => "Sim giá 10 - 50 triệu",
            "notFilterItem" => ['prices'],
            "link" => "/sim-10-trieu-den-50-trieu",
            "pr" => "10000000-50000000",
            "show_mobile"=> true,
            "priceRange"=>[10000000,50000000],
        ],
        [
            "label" => "50 - 100 triệu",
            "name" => "50 - 100 triệu",
            "h1" => "Sim số đẹp giá 50 - 100 triệu",
            "title" => "Sim giá 50 - 100 triệu",
            "notFilterItem" => ['prices'],
            "link" => "/sim-50-trieu-den-100-trieu",
            "pr" => "50000000-100000000",
            "show_mobile"=> true,
            "priceRange"=>[10000000,50000000],
        ],
        [
            "label" => "Trên 100 triệu",
            "name" => "100 - 200 triệu",
            "h1" => "Sim số đẹp giá 100 - 200 triệu",
            "title" => "Sim 100 - 200 triệu",
            "notFilterItem" => ['prices'],
            "link" => "/sim-100-trieu-den-200-trieu",
            "pr" => "100000000-200000000",
            "show_mobile"=> true,
            "priceRange"=>[100000000,200000000],
        ],
        [
            "label" => "200 - 500 triệu",
            "name" => "200 - 500 triệu",
            "h1" => "Sim số đẹp giá 200 - 500 triệu",
            "title" => "Sim 200 - 500 triệu",
            "notFilterItem" => ['prices'],
            "link" => "/sim-200-trieu-den-500-trieu",
            "pr" => "200000000-500000000",
            "show_mobile"=> false,
            "priceRange"=>[200000000,500000000],
        ],
        [
            "label" => "Trên 500 triệu",
            "name" => "Trên 500 triệu",
            "h1" => "Sim số đẹp giá trên 500 triệu",
            "title" => "Sim trên 500 triệu",
            "notFilterItem" => ['prices'],
            "link" => "/sim-tren-500-trieu",
            "pr" => "500000000-10000000000000",
            "show_mobile"=> false,
            "priceRange"=>[500000000,10000000000000],
        ],
    ];
    public const FILTER_TEL = [
        [
            "key" => "viettel",
            "telco" => "viettel",
            "name" => "Viettel",
            "title" => "Sim Viettel",
            "label" => "Sim Viettel",
            "logo" => "/static/[theme_folder]/images/logoTel/viettel.svg",
            "link" => "/sim-viettel",
            "notFilterItem" => ['telco'],
            "show_mobile" => true,
            "t" => "1",
            "heads" => [
                "032",
                "033",
                "034",
                "035",
                "036",
                "037",
                "038",
                "039",
                "096",
                "097",
                "098",
                "086",
            ],
            "filter_mobile_heads" => [
                "09x",
                "03x",
                "098",
                "097",
                "096",
                "086"
            ],
            "priceRange"=>[250000,7900000000],
        ],
        [
            "key" => "vinaphone",
            "telco" => "vinaphone",
            "name" => "Vinaphone",
            "title" => "Sim Vinaphone",
            "label" => "Sim Vinaphone",
            "logo" => "/static/[theme_folder]/images/logoTel/vinaphone.svg",
            "link" => "/sim-so-dep-vinaphone",
            "notFilterItem" => ['telco'],
            "show_mobile" => true,
            "t" => "2",
            "heads" => ["083", "084", "085", "081", "082", "088", "091", "094"],
            "filter_mobile_heads" => [
                "09x",
                "08x",
                "091",
                "094",
                "088",
                "085",
                "084",
                "083",
                "082",
                "081"
            ],
            "priceRange"=>[250000,15000000000],
        ],
        [
            "key" => "mobifone",
            "telco" => "mobifone",
            "name" => "Mobifone",
            "title" => "Sim Mobifone",
            "label" => "Sim Mobifone",
            "logo" => "/static/[theme_folder]/images/logoTel/mobifone.svg",
            "link" => "/sim-so-dep-mobifone",
            "notFilterItem" => ['telco'],
            "show_mobile" => true,
            "t" => "3",
            "heads" => ["070", "076", "077", "078", "079", "089", "090", "093"],
            "filter_mobile_heads" => [
                "09x",
                "07x",
                "090",
                "093",
                "089"
            ],
            "priceRange"=>[220000,112600000000],
        ],
        [
            "key" => "vietnamobile",
            "telco" => "vietnamobile",
            "name" => "Vietnamobile",
            "title" => "Sim Vietnamobile",
            "label" => "Sim Vietnamobile",
            "logo" => "/static/[theme_folder]/images/logoTel/vietnamobile.svg",
            "link" => "/sim-so-dep-vietnamobile",
            "show_mobile" => true,
            "notFilterItem" => ['telco'],
            "t" => "4",
            "heads" => ["052", "056", "058", "092"],
            "filter_mobile_heads" => [
                "092",
                "05x"
            ],
            "priceRange"=>[99000,3000000000],
        ],
        [
            "key" => "itelecom",
            "telco" => "itelecom",
            "name" => "Itel",
            "title" => "Sim iTelecom",
            "label" => "Sim iTelecom",
            "logo" => "/static/[theme_folder]/images/logoTel/itel.svg",
            "link" => "/sim-so-dep-itelecom",
            "notFilterItem" => ['telco'],
            "t" => "8",
            "heads" => ["087"],
            "filter_mobile_heads" => ["087"],
            "priceRange"=>[380000,3500000000],
        ],
        [
            "key" => "wintel",
            "telco" => "wintel",
            "name" => "Wintel",
            "title" => "Sim Wintel",
            "label" => "Sim Wintel",
            "logo" => "/static/[theme_folder]/images/logoTel/wintel.svg",
            "link" => "/sim-so-dep-wintel",
            "notFilterItem" => ['telco'],
            "t" => "9",
            "show_filter"=>false,
            'show_mobile'=>false,
            "heads" => ["055"],
            "filter_mobile_heads" => ["055"],
            "priceRange"=>[99000,3000000000],
        ],
        [
            'key'=>'mayban',
            "telco" => "key",
            'title'=> "Số máy bàn",
            'label'=> "Số máy bàn",
            'name'=> "Số máy bàn",
            'link'=> "/so-may-ban",
            't'=>7,
            "show_filter"=>false,
            'show_mobile'=>false,
            "notFilterItem" => ['telco'],
            "heads" => ["024","022","071","072","074","068","061","031","011","050"],
            "filter_mobile_heads" => [
                "024",
                "022",
                "071",
                "072",
                "074",
                "068",
                "061",
                "031",
                "011",
                "050"
            ],
            "priceRange"=>[250000,15000000000],
        ],
        [
            'key'=>'gmobile',
            'telco'=>'gmobile',
            'title'=> "Sim số đẹp Gmobile",
            'label'=> "Sim số đẹp Gmobile",
            'name'=> "Sim số đẹp Gmobile",
            'link'=> "/sim-so-dep-gmobile",
            't'=>5,
            "priceRange"=>[250000,15000000000],
            "show_filter"=>false,
            'show_mobile'=>false,
        ],
    ];
    public const FILTER_HEAD = [
        [
            "name" => "09x",
            "h" => "09",
            "title" => "Sim Đầu Số 09",
            "label" => "Đầu 09",
            "notFilterItem" => ['head'],
            "link" => "/sim-dau-so-09",
            "priceRange"=>[260000,11265500000],
        ],
        [
            "name" => "08x",
            "h" => "08",
            "title" => "Sim Đầu Số 08",
            "label" => "Đầu 08",
            "notFilterItem" => ['head'],
            "link" => "/sim-dau-so-08",
            "priceRange"=>[260000,15000000000],
        ],
        [
            "name" => "07x",
            "h" => "07",
            "title" => "Sim Đầu Số 07",
            "label" => "Đầu 07",
            "notFilterItem" => ['head'],
            "link" => "/sim-dau-so-07",
            "priceRange"=>[209000,112600000000],
        ],
        [
            "name" => "05x",
            "h" => "05",
            "title" => "Sim Đầu Số 05",
            "label" => "Đầu 05",
            "notFilterItem" => ['head'],
            "link" => "/sim-dau-so-05",
            "priceRange"=>[260000,112600000000],
        ],
        [
            "name" => "03x",
            "h" => "03",
            "title" => "Sim Đầu Số 03",
            "label" => "Đầu 03",
            "notFilterItem" => ['head'],
            "link" => "/sim-dau-so-03",
            "priceRange"=>[238000,6160000000],
        ]
    ];
    public const FILTER_FATES = [
        [
            "c" => "114",
            "name" => "Kim",
            "title" => "Sim Mệnh Kim",
            "label" => "Sim Mệnh Kim",
            "logo" => "/static/[theme_folder]/images/sidebar/logo_kim.svg",
            "link" => "/sim-hop-menh-kim",
            "showCat" => [],
            "notFilterItem" => ['types'],
            "priceRange"=>[260000,7900000000],
        ],
        [
            "c" => "112",
            "name" => "Mộc",
            "title" => "Sim Mệnh Mộc",
            "label" => "Sim Mệnh Mộc",
            "logo" => "/static/[theme_folder]/images/sidebar/logo_moc.svg",
            "link" => "/sim-hop-menh-moc",
            "showCat" => [],
            "notFilterItem" => ['types'],
            "priceRange"=>[105000,5456000000],
        ],
        [
            "c" => "110",
            "name" => "Thuỷ",
            "title" => "Sim Mệnh Thuỷ",
            "label" => "Sim Mệnh Thủy",
            "logo" => "/static/[theme_folder]/images/sidebar/logo_thuy.svg",
            "link" => "/sim-hop-menh-thuy",
            "showCat" => [],
            "notFilterItem" => ['types'],
            "priceRange"=>[260000,112600000000],
        ],
        [
            "c" => "111",
            "name" => "Hoả",
            "title" => "Sim Mệnh Hoả",
            "label" => "Sim Mệnh Hỏa",
            "logo" => "/static/[theme_folder]/images/sidebar/logo_hoa.svg",
            "link" => "/sim-hop-menh-hoa",
            "showCat" => [],
            "notFilterItem" => ['types'],
            "priceRange"=>[114000,11265500000],
        ],
        [
            "c" => "113",
            "name" => "Thổ",
            "title" => "Sim Mệnh Thổ",
            "label" => "Sim Mệnh Thổ",
            "logo" => "/static/[theme_folder]/images/sidebar/logo_tho.svg",
            "link" => "/sim-hop-menh-tho",
            "showCat" => [],
            "notFilterItem" => ['types'],
            "priceRange"=>[260000,15000000000],
        ],
    ];

    public const FILTER_YEAR = [
        [
            "label" => "x1996",
            "name" => "Sim năm sinh 1996",
            "title" => "Sim năm sinh 1996",
            "c" => '77',
            "query" => ["*1996"],
            "link" => "/sim-nam-sinh-1996.html",
            "notFilterItem" => ['types'],
            "priceRange"=>[475000,46350000],
        ],
        [
            "label" => "x1995",
            "name" => "Sim năm sinh 1995",
            "title" => "Sim năm sinh 1995",
            "c" => '77',
            "query" => ["*1995"],
            "link" => "/sim-nam-sinh-1995.html",
            "notFilterItem" => ['types'],
            "priceRange"=>[475000,39000000],
        ],
        [
            "label" => "x1994",
            "name" => "Sim năm sinh 1994",
            "title" => "Sim năm sinh 1994",
            "c" => '77',
            "query" => ["*1994"],
            "link" => "/sim-nam-sinh-1994.html",
            "notFilterItem" => ['types'],
            "priceRange"=>[475000,59650000],
        ],
        [
            "label" => "x1993",
            "name" => "Sim năm sinh 1993",
            "title" => "Sim năm sinh 1993",
            "c" => '77',
            "query" => ["*1993"],
            "link" => "/sim-nam-sinh-1993.html",
            "notFilterItem" => ['types'],
            "priceRange"=>[475000,68990000],
        ],
        [
            "label" => "x1992",
            "name" => "Sim năm sinh 1992",
            "title" => "Sim năm sinh 1992",
            "c" => '77',
            "query" => ["*1992"],
            "link" => "/sim-nam-sinh-1992.html",
            "notFilterItem" => ['types'],
            "priceRange"=>[475000,69650000],
        ],
        [
            "label" => "x1991",
            "name" => "Sim năm sinh 1991",
            "title" => "Sim năm sinh 1991",
            "c" => '77',
            "query" => ["*1991"],
            "link" => "/sim-nam-sinh-1991.html",
            "notFilterItem" => ['types'],
            "priceRange"=>[475000,102200000],
        ],
        [
            "label" => "x1990",
            "name" => "Sim năm sinh 1990",
            "title" => "Sim năm sinh 1990",
            "c" => '77',
            "query" => ["*1990"],
            "link" => "/sim-nam-sinh-1990.html",
            "notFilterItem" => ['types'],
            "priceRange"=>[238000,247800000],
        ],
        [
            "label" => "x1989",
            "name" => "Sim năm sinh 1989",
            "title" => "Sim năm sinh 1989",
            "c" => '77',
            "query" => ["*1989"],
            "link" => "/sim-nam-sinh-1989.html",
            "notFilterItem" => ['types'],
            "priceRange"=>[513000,67290000],
        ],
        [
            "label" => "x1988",
            "name" => "Sim năm sinh 1988",
            "title" => "Sim năm sinh 1988",
            "c" => '77',
            "query" => ["*1988"],
            "link" => "/sim-nam-sinh-1988.html",
            "notFilterItem" => ['types'],
            "priceRange"=>[418000,99290000],
        ],
        [
            "label" => "x1987",
            "name" => "Sim năm sinh 1987",
            "title" => "Sim năm sinh 1987",
            "c" => '77',
            "query" => ["*1987"],
            "link" => "/sim-nam-sinh-1987.html",
            "notFilterItem" => ['types'],
            "priceRange"=>[456000,39000000],
        ],
        [
            "label" => "x1986",
            "name" => "Sim năm sinh 1986",
            "title" => "Sim năm sinh 1986",
            "c" => '77',
            "query" => ["*1986"],
            "link" => "/sim-nam-sinh-1986.html",
            "notFilterItem" => ['types'],
            "priceRange"=>[418000,188000000],
        ],
        [
            "label" => "x1985",
            "name" => "Sim năm sinh 1985",
            "title" => "Sim năm sinh 1985",
            "c" => '77',
            "query" => ["*1985"],
            "link" => "/sim-nam-sinh-1985.html",
            "notFilterItem" => ['types'],
            "priceRange"=>[238000,39000000],
        ],
    ];
    public const FILTER_SORT = [
        [
            'd' => 0,
            'title'=> "Mới cập nhật"
        ],
        [
            'd' => 1,
            'title'=> "Giá cao đến thấp"
        ],
        [
            'd' => -1,
            'title'=> "Giá thấp đến cao"
        ]
    ];

    public const FILTER_CATE_OTHER = [
        [
            'name'=> "Sim Cát",
            'title'=> "Sim Cát",
            'label'=> "Sim Cát",
            'link'=> "/sim-cat",
            'c'=> "116",
            "priceRange"=>[260000,11880000000],
        ],
        [
            'name'=> "Sim Tiến Lên",
            'title'=> "Sim Tiến Lên",
            'label'=> "Sim Tiến Lên",
            'c'=> "81",
            'link'=> "/sim-tien-len",
            "priceRange"=>[133000,15000000000],
        ],
        [
            'name'=> "Sim Đôi",
            'title'=> "Sim Đôi",
            'label'=> "Sim Đôi",
            'c'=> "71",
            'link'=> "/sim-doi",
            "priceRange"=>[4890000,1220000],
        ],
        // Duong add
        // Sim Lap
        [
            'title'=> "Sim Lặp",
            'name'=> "Sim Lặp",
            'label'=> "Sim Lặp",
            'c'=> '123',
            'link'=> "/sim-lap",
            "priceRange"=>[260000,11880000000],
        ],
        [
            'title'=> "Sim Lặp 2",
            'name'=> "Sim Lặp 2",
            'label'=> "Sim Lặp 2",
            'c'=> '123',
            'notInCates'=>[124,125],
            'link'=> "/sim-lap-2",
            "priceRange"=>[260000,695500000],
        ],
        [
            'title'=> "Sim Lặp 3",
            'name'=> "Sim Lặp 3",
            'label'=> "Sim Lặp 3",
            'c'=> '124',
            'link'=> "/sim-lap-3",
            "priceRange"=>[5870000,1782000000],
        ],
        [
            'title'=> "Sim Lặp 4",
            'name'=> "Sim Lặp 4",
            'label'=> "Sim Lặp 4",
            'c'=> '125',
            'link'=> "/sim-lap-4",
            "priceRange"=>[155400000,11880000000],
        ],
        // Sim Kep
        [
            'title'=> "Sim Kép",
            'name'=> "Sim Kép",
            'label'=> "Sim Kép",
            'c'=> '120',
            'link'=> "/sim-kep",
            "priceRange"=>[260000,11880000000],
        ],
        [
            'title'=> "Sim Kép 2",
            'name'=> "Sim Kép 2",
            'label'=> "Sim Kép 2",
            'query'=> ["*0011","*0022","*0033","*0044","*0055","*0066","*0077","*0088","*1100","*1122","*1133","*1144","*1155","*1166","*1177","*1188","*2200","*2211","*2233","*2244","*2255","*2266","*2277","*2288","*3300","*3311","*3322","*3344","*3355","*3366","*3377","*3388","*4400","*4411","*4422","*4433","*4455","*4466","*4477","*4488","*5500","*5511","*5522","*5533","*5544","*5566","*5577","*5588","*6600","*6611","*6622","*6633","*6644","*6655","*6677","*6688","*7700","*7711","*7722","*7733","*7744","*7755","*7766","*7788","*8800","*8811","*8822","*8833","*8844","*8855","*8866","*8877"],
            'c'=> '67',
            'notInCates'=>[121,122],
            'link'=> "/sim-kep-2",
            "priceRange"=>[260000,662500000],
        ],
        [
            'title'=> "Sim Kép 3",
            'name'=> "Sim Kép 3",
            'label'=> "Sim Kép 3",
            'c'=> '121',
            'link'=> "/sim-kep-3",
            "priceRange"=>[105000,1390000000],
        ],
        [
            'title'=> "Sim Kép 4",
            'name'=> "Sim Kép 4",
            'label'=> "Sim Kép 4",
            'c'=> '122',
            'link'=> "/sim-kep-4",
            "priceRange"=>[114000,2979000000],
        ],
        // Sim Taxi
        [
            'title'=> "Sim Taxi 2",
            'label'=> "Sim Taxi 2",
            'name' => "Sim Taxi 2",
            'c'=> "127",
            'link'=> "/sim-taxi-2",
            "priceRange"=>[5870000,11880000000],
        ],
        [
            'title'=> "Sim Taxi 3",
            'label'=> "Sim Taxi 3",
            'name'=> "Sim Taxi 3",
            'c'=> "126",
            'link'=> "/sim-taxi-3",
            "priceRange"=>[474000,1485000000],
        ],
        [
            'title'=> "Sim Taxi 4",
            'label'=> "Sim Taxi 4",
            'name'=> "Sim Taxi 4",
            'c'=> "128",
            'link'=> "/sim-taxi-4",
            "priceRange"=>[713000,11880000000],
        ],
        // Sim tien len
        [
            'title'=> "Sim Tiến Đôi",
            'name'=> "Sim Tiến Đôi",
            'label'=> "Tiến Lên Đôi",
            'link'=> "/sim-tien-doi",
            'query' => ['*001122','*112233','*223344','*334455','*445566','*556677','*667788','*12131415', '*232425','*343536','*454647','*565758','*676869'],
            "priceRange"=>[1540000,2979000000],
        ],
        [
            'title'=> "Sim Tiến 3",
            'label'=> "Sim Tiến 3",
            'name'=> "Sim Tiến 3",
            'link'=> "/sim-tien-3",
            'query'=> ['*012','*123','*234','*345','*456','*567','*678','*789'],
            'queryNotIn'=> ['*0123','*1234','*2345','*3456','*4567','*5678','*6789'],
            "priceRange"=>[238000,792000000],
        ],
        [
            'title'=> "Sim Tiến 4",
            'label'=> "Sim Tiến 4",
            'name'=> "Sim Tiến 4",
            'link'=> "/sim-tien-4",
            'query'=> ['*0123','*1234','*2345','*3456','*4567','*5678','*6789'],
            'queryNotIn'=> ['*01234','*12345','*23456','*34567','*45678','*56789'],
            "priceRange"=>[133000,1842000000],
        ],
        [
            'title'=> "Sim Tiến 5",
            'label'=> "Sim Tiến 5",
            'name'=> "Sim Tiến 5",
            'link'=> "/sim-tien-5",
            'query'=> ['*01234','*12345','*23456','*34567','*45678','*56789'],
            'queryNotIn'=> ['*012345','*123456','*234567','*345678','*456789'],
            "priceRange"=>[2990000,943000000],
        ],
        [
            'title'=> "Sim Tiến 6",
            'label'=> "Sim tiến 6",
            'name'=> "Sim Tiến 6",
            'link'=> "/sim-tien-6",
            'query'=> ['*012345','*123456','*234567','*345678','*456789','*0123456','*01234567','*1234567', '*2345678', '*3456789','*12345678','*23456789'],
            "priceRange"=>[46350000,15000000000],
        ],
        [
            'title'=> "Sim Số Đẹp 4G",
            'label'=> "Sim Số Đẹp 4G",
            'name'=> "Sim Số Đẹp 4G",
            'link'=> "/sim-4g.html",
            "priceRange"=>[250000,15000000000],
        ],
        [
            'key'=>'simtuchon',
            'title'=> "Sim tự chọn",
            'label'=> "Sim tự chọn",
            'name'=> "Sim tự chọn",
            'link'=> "/sim-tu-chon",
            'c'=>'84',
            "priceRange"=>[250000,15000000000],
        ],
    ];
}



// // * Sidebar
// export const filterPrice = [
//   [
//     'key'=> "0",
//     'name'=> "< 500 K",
//     'title'=> "Sim Giá < 500 Nghìn",
//     'label'=> "Sim Giá < 500 Nghìn",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-duoi-500-nghin",
//     'minPrice'=> "0",
//     'maxPrice'=> "500000",
//   ],
//   [
//     'key'=> "500000",
//     'name'=> "500 - 1 Tr",
//     'title'=> "Sim Giá 500 - 1 Triệu",
//     'label'=> "Sim Giá 500 - 1 Triệu",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-500-nghin-den-1-trieu",
//     'minPrice'=> "500000",
//     'maxPrice'=> "1000000",
//   ],
//   [
//     'key'=> "1000000",
//     'name'=> "1 - 3 Tr",
//     'title'=> "Sim Giá 1 - 3 Triệu",
//     'label'=> "Sim Giá 1 - 3 Triệu",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-1-trieu-den-3-trieu",
//     'minPrice'=> "1000000",
//     'maxPrice'=> "3000000",
//   ],
//   [
//     'key'=> "3000000",
//     'name'=> "3 - 5 Tr",
//     'title'=> "Sim Giá 3 - 5 Triệu",
//     'label'=> "Sim Giá 3 - 5 Triệu",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-3-trieu-den-5-trieu",
//     'minPrice'=> "3000000",
//     'maxPrice'=> "5000000",
//   ],
//   [
//     'key'=> "5000000",
//     'name'=> "5 - 10 Tr",
//     'title'=> "Sim Giá 5 - 10 Triệu",
//     'label'=> "Sim Giá 5 - 10 Triệu",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-5-trieu-den-10-trieu",
//     'minPrice'=> "5000000",
//     'maxPrice'=> "10000000",
//   ],
//   [
//     'key'=> "10000000",
//     'name'=> "10 - 30 Tr",
//     'title'=> "Sim Giá 10 - 30 Triệu",
//     'label'=> "Sim Giá 10 - 30 Triệu",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-10-trieu-den-30-trieu",
//     'minPrice'=> "10000000",
//     'maxPrice'=> "30000000",
//   ],
//   [
//     'key'=> "30000000",
//     'name'=> "30 - 50 Tr",
//     'title'=> "Sim Giá 30 - 50 Triệu",
//     'label'=> "Sim Giá 30 - 50 Triệu",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-30-trieu-den-50-trieu",
//     'minPrice'=> "30000000",
//     'maxPrice'=> "50000000",
//   ],
//   [
//     'key'=> "50000000",
//     'name'=> "50 - 80 Tr",
//     'title'=> "Sim Giá 50 - 80 Triệu",
//     'label'=> "Sim Giá 50 - 80 Triệu",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-50-trieu-den-80-trieu",
//     'minPrice'=> "50000000",
//     'maxPrice'=> "80000000",
//   ],
//   [
//     'key'=> "80000000",
//     'name'=> "80 - 100 Tr",
//     'title'=> "Sim Giá 80 - 100 Triệu",
//     'label'=> "Sim Giá 80 - 100 Triệu",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-80-trieu-den-100-trieu",
//     'minPrice'=> "80000000",
//     'maxPrice'=> "100000000",
//   ],
//   [
//     'key'=> "100000000",
//     'name'=> "100 - 150 Tr",
//     'title'=> "Sim Giá 100 - 150 Triệu",
//     'label'=> "Sim Giá 100 - 150 Triệu",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-100-trieu-den-150-trieu",
//     'minPrice'=> "100000000",
//     'maxPrice'=> "150000000",
//   ],
//   [
//     'key'=> "150000000",
//     'name'=> "150 - 200 Tr",
//     'title'=> "Sim Giá 150 - 200 Triệu",
//     'label'=> "Sim Giá 150 - 200 Triệu",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-150-trieu-den-200-trieu",
//     'minPrice'=> "150000000",
//     'maxPrice'=> "200000000",
//   ],
//   [
//     'key'=> "200000000",
//     'name'=> "200 - 300 Tr",
//     'title'=> "Sim Giá 200 - 300 Triệu",
//     'label'=> "Sim Giá 200 - 300 Triệu",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-200-trieu-den-300-trieu",
//     'minPrice'=> "200000000",
//     'maxPrice'=> "300000000",
//   ],
//   [
//     'key'=> "300000000",
//     'name'=> "300 - 500 Tr",
//     'title'=> "Sim Giá 300 - 500 Triệu",
//     'label'=> "Sim Giá 300 - 500 Triệu",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-300-trieu-den-500-trieu",
//     'minPrice'=> "300000000",
//     'maxPrice'=> "500000000",
//   ],
//   [
//     'key'=> "500000000",
//     'name'=> "500 - 1 Tỷ",
//     'title'=> "Sim Giá 500 - 1 Tỷ",
//     'label'=> "Sim Giá 500 - 1 Tỷ",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-tu-500-trieu-den-1-ti",
//     'minPrice'=> "500000000",
//     'maxPrice'=> "1000000000",
//   ],
//   // them
//   [
//     'key'=> "1000000000",
//     'name'=> "> 1 Tỷ",
//     'title'=> "Sim Giá Trên 1 Tỷ",
//     'label'=> "Sim Giá Trên 1 Tỷ",
//     'notFilterItem'=> ['prices'],
//     'link'=> "/sim-gia-so-dep-lon-hon-1-ti",
//     'minPrice'=> "1000000000",
//     'maxPrice'=> "10000000000000",
//   ],
// ];

// export const filterTel = [
//   [
//     'key'=> "viettel",
//     'telco'=> "viettel",
//     'name'=> "Viettel",
//     'title'=> "Sim Viettel",
//     'label'=> "Sim Viettel",
//     'logo'=> "/images/viettel.svg",
//     'link'=> "/sim-viettel",
//     'notFilterItem'=> ['telco'],
//     't'=> "1",
//     'dis_home'=> true,
//     'heads'=> [
//       "032",
//       "033",
//       "034",
//       "035",
//       "036",
//       "037",
//       "038",
//       "039",
//       "096",
//       "097",
//       "098",
//       "086",
//     ],
//   ],
//   [
//     'key'=> "vinaphone",
//     'telco'=> "vinaphone",
//     'name'=> "Vinaphone",
//     'title'=> "Sim Vinaphone",
//     'label'=> "Sim Vinaphone",
//     'logo'=> "/images/vinaphone.svg",
//     'link'=> "/sim-vinaphone",
//     'notFilterItem'=> ['telco'],
//     't'=> "2",
//     'dis_home'=> true,
//     'heads'=> ["083", "084", "085", "081", "082", "088", "091", "094"],
//   ],
//   [
//     'key'=> "mobifone",
//     'telco'=> "mobifone",
//     'name'=> "Mobifone",
//     'title'=> "Sim Mobifone",
//     'label'=> "Sim Mobifone",
//     'logo'=> "/images/mobifone.svg",
//     'link'=> "/sim-mobifone",
//     'notFilterItem'=> ['telco'],
//     't'=> "3",
//     'dis_home'=> true,
//     'heads'=> ["070", "076", "077", "078", "079", "089", "090", "093"],
//   ],
//   [
//     'key'=> "itelecom",
//     'telco'=> "itelecom",
//     'name'=> "Itel",
//     'title'=> "Sim Itel",
//     'label'=> "Sim Itel",
//     'logo'=> "/images/itelecom.svg",
//     'link'=> "/sim-itelecom",
//     'notFilterItem'=> ['telco'],
//     't'=> "8",
//     'dis_home'=> true,
//     'heads'=> ["087"],
//   ],
//   [
//     'key'=> "vietnamobile",
//     'telco'=> "vietnamobile",
//     'name'=> "Vietnamobile",
//     'title'=> "Sim Vietnamobile",
//     'label'=> "Sim Vietnamobile",
//     'logo'=> "/images/vietnamobile.svg",
//     'link'=> "/sim-vietnamobile",
//     'notFilterItem'=> ['telco'],
//     't'=> "4",
//     'dis_home'=> true,
//     'heads'=> ["056", "058", "092"],
//   ],
//   // [
//   //   'key'=> "gmobile",
//   //   'telco'=> "gmobile",
//   //   'name'=> "G-mobile",
//   //   'title'=> "Sim G-mobile",
//   //   'label'=> "Sim G-mobile",
//   //   'logo'=> "/images/gmobile.svg",
//   //   'notFilterItem'=> ['telco'],
//   //   'link'=> "/sim-gmobile",
//   //   'dis_home'=> true,
//   //   't'=> "5",
//   //   'heads'=> ["059", "099"],
//   // ],
//   [
//     'key'=> "telephone",
//     'telco'=> "telephone",
//     'name'=> "Máy bàn",
//     'title'=> "Sim máy bàn",
//     'logo'=> "images/telephone.svg",
//     'link'=> "/sim-may-ban",
//     't'=> "7",
//     'heads'=> [],
//   ],
// ];

// export const filterHead = [
//   [
//     'name'=> "09x",
//     'key'=> "09",
//     'head'=> "09",
//     'title'=> "Sim Đầu Số 09",
//     'label'=> "Sim Đầu Số 09",
//     'notFilterItem'=> ['head'],
//     'link'=> "/sim-dau-so-09",
//   ],
//   [
//     'name'=> "08x",
//     'key'=> "08",
//     'head'=> "08",
//     'title'=> "Sim Đầu Số 08",
//     'label'=> "Sim Đầu Số 08",
//     'notFilterItem'=> ['head'],
//     'link'=> "/sim-dau-so-08",
//   ],
//   [
//     'name'=> "07x",
//     'key'=> "07",
//     'head'=> "07",
//     'title'=> "Sim Đầu Số 07",
//     'label'=> "Sim Đầu Số 07",
//     'notFilterItem'=> ['head'],
//     'link'=> "/sim-dau-so-07",
//   ],
//   [
//     'name'=> "05x",
//     'key'=> "05",
//     'head'=> "05",
//     'title'=> "Sim Đầu Số 05",
//     'label'=> "Sim Đầu Số 05",
//     'notFilterItem'=> ['head'],
//     'link'=> "/sim-dau-so-05",
//   ],
//   [
//     'name'=> "03x",
//     'key'=> "03",
//     'head'=> "03",
//     'title'=> "Sim Đầu Số 03",
//     'label'=> "Sim Đầu Số 03",
//     'notFilterItem'=> ['head'],
//     'link'=> "/sim-dau-so-03",
//   ],
// ];

// export const filterPhongThuy = [
//   [
//     'id'=> 27,
//     'name'=> "Kim",
//     'title'=> "Kim",
//     'label'=> "Kim",
//     'bgPosition'=> "-126px 0px",
//     'bgSize'=> "280px 120px",
//     'catId'=> 114,
//     'link'=> "/sim-hop-menh-kim",
//   ],
//   [
//     'id'=> 28,
//     'name'=> "Mộc",
//     'title'=> "Mộc",
//     'label'=> "Mộc",
//     'bgPosition'=> "-84px 0px",
//     'bgSize'=> "280px 120px",
//     'catId'=> 112,
//     'link'=> "/sim-hop-menh-moc",
//   ],
//   [
//     'id'=> 29,
//     'name'=> "Thủy",
//     'title'=> "Thủy",
//     'label'=> "Thủy",
//     'bgPosition'=> "0px 0px",
//     'bgSize'=> "280px 120px",
//     'catId'=> 110,
//     'link'=> "/sim-hop-menh-thuy",
//   ],
//   [
//     'id'=> 30,
//     'name'=> "Hỏa",
//     'title'=> "Hỏa",
//     'label'=> "Hỏa",
//     'bgPosition'=> "-169px 0px",
//     'bgSize'=> "280px 120px",
//     'catId'=> 111,
//     'link'=> "/sim-hop-menh-hoa",
//   ],
//   [
//     'id'=> 31,
//     'name'=> "Thổ",
//     'title'=> "Thổ",
//     'label'=> "Thổ",
//     'bgPosition'=> "-43px 0px",
//     'bgSize'=> "280px 120px",
//     'catId'=> 113,
//     'link'=> "/sim-hop-menh-tho",
//   ],
// ];

// export const filterHighLevel = [
//   [
//     'id'=> 32,
//     'title'=> "VIP",
//     'name'=> "Sim VIP",
//     'label'=> "Sim VIP",
//     'catId'=> "82",
//     'link'=> "/sim-vip",
//   ],
//   [
//     'id'=> 33,
//     'title'=> "666.666",
//     'name'=> "Sim Lục Quý",
//     'label'=> "Sim Lục Quý",
//     'catId'=> "100",
//     'link'=> "/sim-luc-quy",
//   ],
//   [
//     'id'=> 35,
//     'title'=> "55555",
//     'name'=> "Sim Ngũ Quý",
//     'label'=> "Sim Ngũ Quý",
//     'catId'=> "99",
//     'link'=> "/sim-ngu-quy",
//   ],
// ];

// export const filterImpressive = [
//   [
//     'id'=> 40,
//     'label'=> "4444",
//     'title'=> "Sim Tứ Quý",
//     'name'=> "Sim Tứ Quý",
//     'catId'=> "68",
//     'link'=> "/sim-tu-quy",
//     'showCat'=> [],
//     'notFilterItem'=> ['category'],
//   ],


//   [
//     'id'=> 44,
//     'label'=> "AB.AB",
//     'title'=> "Sim Lặp",
//     'name'=> "Sim Lặp",
//     'catId'=> "123",
//     'link'=> "/sim-lap",
//     'showCat'=>["/sim-lap-2","/sim-lap-3","/sim-lap-4"],
//     'redirect'=> true
//   ],

//   [
//     'id'=> 47,
//     'label'=> "ABC.ABC",
//     'title'=> "Sim Taxi",
//     'name'=> "Sim Taxi",
//     'catId'=> "74",
//     'link'=> "/sim-taxi",
//     'showCat'=>["/sim-taxi-2","/sim-taxi-3","/sim-taxi-4"],

//   ],
//   [
//     'id'=> 48,
//     'label'=> "75.78.78",
//     'title'=> "Sim Số Độc",
//     'name'=> "Sim Số Độc",
//     'catId'=> "78",
//     'link'=> "/sim-so-doc",
//   ],
//   [
//     'id'=> 49,
//     'label'=> "09x",
//     'title'=> "Sim Đầu Số Cổ",
//     'name'=> "Sim Đầu Số Cổ",
//     'query'=> ["090*", "091*", "093*", "094*", "096*", "090*", "097*", "098*"],
//     'link'=> "/sim-dau-so-co",
//   ],
// ];




// export const filterDoubleDigits = [

//   [
//     'catId'=> "120",
//     'label'=> "Sim Kép",
//     'title'=> "Sim Kép",
//     'name'=> "Sim Kép",
//     'link'=> "/sim-kep",
//     'showCat'=>["/sim-kep-2","/sim-kep-3","/sim-kep-4"],
//     'redirect'=> true
//   ],
//   [
//     'label'=> "Sim Kép 2",
//     'title'=> "Sim Kép 2",
//     'name'=> "Sim Kép 2",
//     'link'=> "/sim-kep-2",
//     'query'=> ["*0011","*0022","*0033","*0044","*0055","*0066","*0077","*0088","*1100","*1122","*1133","*1144","*1155","*1166","*1177","*1188","*2200","*2211","*2233","*2244","*2255","*2266","*2277","*2288","*3300","*3311","*3322","*3344","*3355","*3366","*3377","*3388","*4400","*4411","*4422","*4433","*4455","*4466","*4477","*4488","*5500","*5511","*5522","*5533","*5544","*5566","*5577","*5588","*6600","*6611","*6622","*6633","*6644","*6655","*6677","*6688","*7700","*7711","*7722","*7733","*7744","*7755","*7766","*7788","*8800","*8811","*8822","*8833","*8844","*8855","*8866","*8877"],
//     'catId'=> '67',
//     'notInCates'=>[121,122],
//     'showCat'=>[],
//     'notFilterItem'=> ['category'],
//     'redirect'=> true,
//     'breadcrumb'=> ['<a href="/sim-kep">Sim Kép</a>']
//   ],
//   [
//     'catId'=> "121",
//     'label'=> "Sim Kép 3",
//     'title'=> "Sim Kép 3",
//     'name'=> "Sim Kép 3",
//     'link'=> "/sim-kep-3",
//     'showCat'=>[],
//     'notFilterItem'=> ['category'],
//     'redirect'=> true,
//     'breadcrumb'=> ['<a href="/sim-kep">Sim Kép</a>']
//   ],
//   [
//     'catId'=> "122",
//     'label'=> "Sim Kép 4",
//     'title'=> "Sim Kép 4",
//     'name'=> "Sim Kép 4",
//     'link'=> "/sim-kep-4",
//     'showCat'=>[],
//     'notFilterItem'=> ['category'],
//     'redirect'=> true,
//     'breadcrumb'=> ['<a href="/sim-kep">Sim Kép</a>']
//   ],
//   [
//     'label'=> "Sim Lặp 2",
//     'title'=> "Sim Lặp 2",
//     'name'=> "Sim Lặp 2",
//     'link'=> "/sim-lap-2",
//     'catId'=> '123',
//     'notInCates'=> "124,125",
//     'showCat'=>[],
//     'notFilterItem'=> ['category'],
//     'redirect'=> true,
//     'breadcrumb'=> ['<a href="/sim-lap">Sim Lặp</a>']
//   ],
//   [
//     'catId'=> "124",
//     'label'=> "Sim Lặp 3",
//     'title'=> "Sim Lặp 3",
//     'name'=> "Sim Lặp 3",
//     'link'=> "/sim-lap-3",
//     'showCat'=>[],
//     'notFilterItem'=> ['category'],
//     'redirect'=> true,
//     'breadcrumb'=> ['<a href="/sim-lap">Sim Lặp</a>']
//   ],
//   [
//     'catId'=> "125",
//     'label'=> "Sim Lặp 4",
//     'title'=> "Sim Lặp 4",
//     'name'=> "Sim Lặp 4",
//     'link'=> "/sim-lap-4",
//     'showCat'=>[],
//     'notFilterItem'=> ['category'],
//     'redirect'=> true,
//     'breadcrumb'=> ['<a href="/sim-lap">Sim Lặp</a>']
//   ],
// ];

// export const filterPopularKeyword = [

//   [
//     'id'=> 55,
//     'name'=> "Sim Tứ Quý 9",
//     'title'=> "Sim Tứ Quý 9",
//     'label'=> "Sim Tứ Quý 9",
//     'catId'=> "68",
//     'tail'=> '9999',
//     'link'=> "/sim-tu-quy-9999",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
//   ],
//   [
//     'id'=> 56,
//     'name'=> "Sim Tam Hoa 0",
//     'title'=> "Sim Tam Hoa 0",
//     'label'=> "Sim Tam Hoa 0",
//     'catId'=> "80",
//     'tail'=> '000',
//     'link'=> "/sim-tam-hoa-000",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
//   ],
//   [
//     'id'=> 56,
//     'name'=> "Sim Tam Hoa 5",
//     'title'=> "Sim Tam Hoa 5",
//     'label'=> "Sim Tam Hoa 5",
//     'catId'=> "80",
//     'tail'=> '555',
//     'link'=> "/sim-tam-hoa-555",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
//   ],
//   [
//     'id'=> 55,
//     'name'=> "Sim Tứ Quý 0",
//     'title'=> "Sim Tứ Quý 0",
//     'label'=> "Sim Tứ Quý 0",
//     'catId'=> "68",
//     'tail'=> '0000',
//     'link'=> "/sim-tu-quy-0000",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
//   ],
//   [
//     'id'=> 56,
//     'name'=> "Sim Tam Hoa 1",
//     'title'=> "Sim Tam Hoa 1",
//     'label'=> "Sim Tam Hoa 1",
//     'catId'=> "80",
//     'tail'=> '111',
//     'link'=> "/sim-tam-hoa-111",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
//   ],
//   [
//     'id'=> 57,
//     'name'=> "Sim Tam Hoa 2",
//     'title'=> "Sim Tam Hoa 2",
//     'label'=> "Sim Tam Hoa 2",
//     'catId'=> "80",
//     'tail'=> 222,
//     'link'=> "/sim-tam-hoa-222",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
//   ],
//   [
//     'id'=> 56,
//     'name'=> "Sim Tam Hoa 3",
//     'title'=> "Sim Tam Hoa 3",
//     'label'=> "Sim Tam Hoa 3",
//     'catId'=> "80",
//     'tail'=> '333',
//     'link'=> "/sim-tam-hoa-333",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
//   ],
//   [
//     'id'=> 58,
//     'name'=> "Sim Tứ Quý 8",
//     'title'=> "Sim Tứ Quý 8",
//     'label'=> "Sim Tứ Quý 8",
//     'catId'=> "68",
//     'tail'=> 8888,
//     'link'=> "/sim-tu-quy-8888",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
//   ],
//   [
//     'id'=> 56,
//     'name'=> "Sim Tam Hoa 4",
//     'title'=> "Sim Tam Hoa 4",
//     'label'=> "Sim Tam Hoa 4",
//     'catId'=> "80",
//     'tail'=> '444',
//     'link'=> "/sim-tam-hoa-444",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
//   ],
//   [
//     'id'=> 59,
//     'name'=> "Sim Tam Hoa 7",
//     'title'=> "Sim Tam Hoa 7",
//     'label'=> "Sim Tam Hoa 7",
//     'catId'=> "80",
//     'tail'=> 777,
//     'link'=> "/sim-tam-hoa-777",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
//   ],
//   [
//     'id'=> 55,
//     'name'=> "Sim Tứ Quý 1",
//     'title'=> "Sim Tứ Quý 1",
//     'label'=> "Sim Tứ Quý 1",
//     'catId'=> "68",
//     'tail'=> '1111',
//     'link'=> "/sim-tu-quy-1111",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
//   ],
//   [
//     'id'=> 60,
//     'name'=> "Sim Tứ Quý 7",
//     'title'=> "Sim Tứ Quý 7",
//     'label'=> "Sim Tứ Quý 7",
//     'catId'=> "68",
//     'tail'=> 7777,
//     'link'=> "/sim-tu-quy-7777",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
//   ],
//   [
//     'id'=> 61,
//     'name'=> "Sim Tam Hoa 9",
//     'title'=> "Sim Tam Hoa 9",
//     'label'=> "Sim Tam Hoa 9",
//     'catId'=> "80",
//     'tail'=> 999,
//     'link'=> "/sim-tam-hoa-999",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
//   ],
//   [
//     'id'=> 55,
//     'name'=> "Sim Tứ Quý 2",
//     'title'=> "Sim Tứ Quý 2",
//     'label'=> "Sim Tứ Quý 2",
//     'catId'=> "68",
//     'tail'=> '2222',
//     'link'=> "/sim-tu-quy-2222",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
//   ],
//   [
//     'id'=> 62,
//     'name'=> "Sim Tứ Quý 6",
//     'title'=> "Sim Tứ Quý 6",
//     'label'=> "Sim Tứ Quý 6",
//     'catId'=> "68",
//     'tail'=> 6666,
//     'link'=> "/sim-tu-quy-6666",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
//   ],
//   [
//     'id'=> 63,
//     'name'=> "Sim Tứ Quý 3",
//     'title'=> "Sim Tứ Quý 3",
//     'label'=> "Sim Tứ Quý 3",
//     'catId'=> "68",
//     'tail'=> 3333,
//     'link'=> "/sim-tu-quy-3333",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
//   ],
//   [
//     'id'=> 64,
//     'name'=> "Sim Tứ Quý 5",
//     'title'=> "Sim Tứ Quý 5",
//     'label'=> "Sim Tứ Quý 5",
//     'catId'=> "68",
//     'tail'=> 5555,
//     'link'=> "/sim-tu-quy-5555",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
//   ],
//   [
//     'id'=> 65,
//     'name'=> "Sim Tam Hoa 8",
//     'title'=> "Sim Tam Hoa 8",
//     'label'=> "Sim Tam Hoa 8",
//     'catId'=> "80",
//     'tail'=> 888,
//     'link'=> "/sim-tam-hoa-888",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
//   ],
//   [
//     'name'=> "Sim Tứ Quý 4",
//     'title'=> "Sim Tứ Quý 4",
//     'label'=> "Sim Tứ Quý 4",
//     'catId'=> "68",
//     'tail'=> '4444',
//     'link'=> "/sim-tu-quy-4444",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tu-quy">Sim Tứ Qúy</a>']
//   ],
//   [
//     'id'=> 66,
//     'name'=> "Sim Tam Hoa 6",
//     'title'=> "Sim Tam Hoa 6",
//     'label'=> "Sim Tam Hoa 6",
//     'catId'=> "80",
//     'tail'=> 666,
//     'link'=> "/sim-tam-hoa-666",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tam-hoa">Sim Tam Hoa</a>']
//   ],
// ];

// export const filterTypes = [
//   [
//     'id'=> 1631,
//     'title'=> "6789",
//     'label'=> "Tiến lên",
//     'catId'=> "81",
//     'link'=> "/sim-tien-len",
//   ],
//   [
//     'id'=> 1632,
//     'title'=> "333",
//     'label'=> "Tam hoa",
//     'catId'=> "80",
//     'link'=> "/sim-tam-hoa",
//   ],
//   [
//     'id'=> 1633,
//     'title'=> "4444",
//     'label'=> "Tứ quý",
//     'catId'=> "68",
//     'link'=> "/sim-tu-quy",
//   ],
//   [
//     'id'=> 1634,
//     'title'=> "68.68",
//     'label'=> "Lộc phát",
//     'catId'=> "73",
//     'link'=> "/sim-loc-phat",
//   ],
//   [
//     'id'=> 1635,
//     'title'=> "55555",
//     'label'=> "Ngũ quý",
//     'catId'=> "99",
//     'link'=> "/sim-ngu-quy",
//   ],
//   [
//     'id'=> 1636,
//     'title'=> "666.666",
//     'label'=> "Lục quý",
//     'catId'=> "100",
//     'link'=> "/sim-luc-quy",
//   ],
//   [
//     'id'=> 1637,
//     'title'=> "333.999",
//     'label'=> "Tam hoa kép",
//     'catId'=> "102",
//     'link'=> "/sim-tam-hoa-kep",
//   ],
//   [
//     'id'=> 1638,
//     'title'=> "AB.BA",
//     'label'=> "Gánh đảo",
//     'catId'=> "79",
//     'link'=> "/sim-ganh-dao",
//   ],
//   [
//     'id'=> 1639,
//     'title'=> "ABC.ABC",
//     'label'=> "Taxi",
//     'catId'=> "74",
//     'link'=> "/sim-taxi",
//   ],
//   [
//     'id'=> 16310,
//     'title'=> "VIP",
//     'label'=> "Sim VIP",
//     'catId'=> "82",
//     'link'=> "/sim-vip",
//   ],
//   [
//     'id'=> 16311,
//     'title'=> "75.78.78",
//     'label'=> "Số độc",
//     'catId'=> "78",
//     'link'=> "/sim-so-doc",
//   ],
//   [
//     'id'=> 16312,
//     'title'=> "AABBCC",
//     'label'=> "Dễ nhớ",
//     'catId'=> "76",
//     'link'=> "/sim-de-nho",
//   ],
//   [
//     'id'=> 16313,
//     'title'=> "AB.AB",
//     'label'=> "Lặp kép",
//     'catId'=> "123",
//     'link'=> "/sim-lap",
//   ],
//   [
//     'id'=> 16314,
//     'label'=> "Năm sinh",
//     'catId'=> "77",
//     'link'=> "/sim-nam-sinh",
//   ],
// ];

// export const filterTienLenTypes = [
//   [
//     'id'=> 3,
//     'title'=> "Sim Tiến 3",
//     'label'=> "Sim Tiến 3",
//     'name'=> "Sim Tiến 3",
//     'link'=> "/sim-tien-3",
//     'query'=> ['*012','*123','*234','*345','*456','*567','*678','*789'],
//     'queryNotIn'=> ['*0123','*1234','*2345','*3456','*4567','*5678','*6789'],
//     'notFilterItem'=> ['category'],
//     'redirect'=> true,
//     'breadcrumb'=> ['<a href="/sim-tien-len">Sim Tiến Lên</a>']
//   ],
//   [
//     'id'=> 3,
//     'title'=> "Sim Tiến Đôi",
//     'name'=> "Sim Tiến Đôi",
//     'label'=> "Tiến Lên Đôi",
//     'link'=> "/sim-tien-doi",
//     'query'=> [
//       '*001122'
//       ,'*112233'
//       ,'*223344'
//       ,'*334455'
//       ,'*445566'
//       ,'*556677'
//       ,'*667788'
//       ,'*12131415'
//       ,'*232425'
//       ,'*343536'
//       ,'*454647'
//       ,'*565758'
//       ,'*676869'
//     ],
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tien-len">Sim Tiến Lên</a>']
//   ],
//   [
//     'id'=> 4,
//     'title'=> "Sim Tiến 4",
//     'label'=> "Sim Tiến 4",
//     'name'=> "Sim Tiến 4",
//     'link'=> "/sim-tien-4",
//     'redirect'=> true,
//     'query'=> ['*0123','*1234','*2345','*3456','*4567','*5678','*6789'],
//     'queryNotIn'=> ['*01234','*12345','*23456','*34567','*45678','*56789'],
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tien-len">Sim Tiến Lên</a>']
//   ],
//   [
//     'id'=> 5,
//     'title'=> "Sim Tiến 5",
//     'label'=> "Sim Tiến 5",
//     'name'=> "Sim Tiến 5",
//     'link'=> "/sim-tien-5",
//     'query'=> ['*01234','*12345','*23456','*34567','*45678','*56789'],
//     'queryNotIn'=> ['*012345','*123456','*234567','*345678','*456789'],
//     'notFilterItem'=> ['category'],
//     'redirect'=> true,
//     'breadcrumb'=> ['<a href="/sim-tien-len">Sim Tiến Lên</a>']
//   ],
//   [
//     'id'=> 6,
//     'title'=> "Sim Tiến 6",
//     'label'=> "Sim tiến 6",
//     'name'=> "Sim Tiến 6",
//     'link'=> "/sim-tien-6",
//     'query'=> ['*012345','*123456','*234567','*345678','*456789','*0123456','*01234567','*1234567', '*2345678', '*3456789',,'*12345678','*23456789'],
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tien-len">Sim Tiến Lên</a>']
//   ],
// ];

// export const FILTER_OTHER = [
//   [
//     'title'=> "Sim Số Đẹp",
//     'name'=> "Sim Số Đẹp",
//     'label'=> "Sim Số Đẹp",
//     'link'=> "/sim-so-dep-dau-so",
//     'breadcrumb'=> ['<a href="/sim-so-dep">Sim Số Đẹp</a>']
//   ],
//   [
//     'title'=> "Sim Số Đẹp",
//     'name'=> "Sim Số Đẹp",
//     'label'=> "Sim Số Đẹp",
//     'link'=> "/sim-so-dep-duoi-so",
//     'breadcrumb'=> ['<a href="/sim-so-dep">Sim Số Đẹp</a>']
//   ],
//   [
//     'title'=> "Sim Lục Quý giữa",
//     'name'=> "Sim Lục Quý giữa",
//     'label'=> "Sim Lục Quý giữa",
//     'link'=> "/sim-luc-quy-giua",
//     'catId'=> '105',
//     'breadcrumb'=> ['<a href="/sim-luc-quy">Sim Lục Quý</a>']
//   ],
//   [
//     'title'=> "Sim Lục Quý 0",
//     'name'=> "Sim Lục Quý 0",
//     'label'=> "Sim Lục Quý 0",
//     'link'=> "/sim-luc-quy-000000",
//     'catId'=> '100',
//     'tail'=> '000000',
//     'breadcrumb'=> ['<a href="/sim-luc-quy">Sim Lục Quý</a>']
//   ],
//   [
//     'title'=> "Sim Lục Quý 1",
//     'name'=> "Sim Lục Quý 1",
//     'label'=> "Sim Lục Quý 1",
//     'link'=> "/sim-luc-quy-111111",
//     'catId'=> '100',
//     'tail'=> '111111',
//     'breadcrumb'=> ['<a href="/sim-luc-quy">Sim Lục Quý</a>']
//   ],
//   [
//     'title'=> "Sim Lục Quý 2",
//     'name'=> "Sim Lục Quý 2",
//     'label'=> "Sim Lục Quý 2",
//     'link'=> "/sim-luc-quy-222222",
//     'catId'=> '100',
//     'tail'=> '222222',
//     'breadcrumb'=> ['<a href="/sim-luc-quy">Sim Lục Quý</a>']
//   ],
//   [
//     'title'=> "Sim Lục Quý 3",
//     'name'=> "Sim Lục Quý 3",
//     'label'=> "Sim Lục Quý 3",
//     'link'=> "/sim-luc-quy-333333",
//     'catId'=> '100',
//     'tail'=> '333333',
//     'breadcrumb'=> ['<a href="/sim-luc-quy">Sim Lục Quý</a>']
//   ],
//   [
//     'title'=> "Sim Lục Quý 4",
//     'name'=> "Sim Lục Quý 4",
//     'label'=> "Sim Lục Quý 4",
//     'link'=> "/sim-luc-quy-444444",
//     'catId'=> '100',
//     'tail'=> '444444',
//     'breadcrumb'=> ['<a href="/sim-luc-quy">Sim Lục Quý</a>']
//   ],
//   [
//     'title'=> "Sim Lục Quý 5",
//     'name'=> "Sim Lục Quý 5",
//     'label'=> "Sim Lục Quý 5",
//     'link'=> "/sim-luc-quy-555555",
//     'catId'=> '100',
//     'tail'=> '555555',
//     'breadcrumb'=> ['<a href="/sim-luc-quy">Sim Lục Quý</a>']
//   ],
//   [
//     'title'=> "Sim Lục Quý 6",
//     'name'=> "Sim Lục Quý 6",
//     'label'=> "Sim Lục Quý 6",
//     'link'=> "/sim-luc-quy-666666",
//     'catId'=> '100',
//     'tail'=> '666666',
//     'breadcrumb'=> ['<a href="/sim-luc-quy">Sim Lục Quý</a>']
//   ],
//   [
//     'title'=> "Sim Lục Quý 7",
//     'name'=> "Sim Lục Quý 7",
//     'label'=> "Sim Lục Quý 7",
//     'link'=> "/sim-luc-quy-777777",
//     'catId'=> '100',
//     'tail'=> '777777',
//     'breadcrumb'=> ['<a href="/sim-luc-quy">Sim Lục Quý</a>']
//   ],
//   [
//     'title'=> "Sim Lục Quý 8",
//     'name'=> "Sim Lục Quý 8",
//     'label'=> "Sim Lục Quý 8",
//     'link'=> "/sim-luc-quy-888888",
//     'catId'=> '100',
//     'tail'=> '888888',
//     'breadcrumb'=> ['<a href="/sim-luc-quy">Sim Lục Quý</a>']
//   ],
//   [
//     'title'=> "Sim Lục Quý 9",
//     'name'=> "Sim Lục Quý 9",
//     'label'=> "Sim Lục Quý 9",
//     'link'=> "/sim-luc-quy-999999",
//     'catId'=> '100',
//     'tail'=> '999999',
//     'breadcrumb'=> ['<a href="/sim-luc-quy">Sim Lục Quý</a>']
//   ],
//   [
//     'title'=> "Sim Ngũ Quý giữa",
//     'name'=> "Sim Ngũ Quý giữa",
//     'label'=> "Sim Ngũ Quý giữa",
//     'link'=> "/sim-ngu-quy-giua",
//     'catId'=> '104',
//     'breadcrumb'=> ['<a href="/sim-ngu-quy">Sim Ngũ Quý</a>']
//   ],
//   [
//     'title'=> "Sim Ngũ Quý 0",
//     'name'=> "Sim Ngũ Quý 0",
//     'label'=> "Sim Ngũ Quý 0",
//     'link'=> "/sim-ngu-quy-00000",
//     'catId'=> '99',
//     'tail'=> "00000",
//     'breadcrumb'=> ['<a href="/sim-ngu-quy">Sim Ngũ Quý</a>']
//   ],
//   [
//     'title'=> "Sim Ngũ Quý 1",
//     'name'=> "Sim Ngũ Quý 1",
//     'label'=> "Sim Ngũ Quý 1",
//     'link'=> "/sim-ngu-quy-11111",
//     'catId'=> '99',
//     'tail'=> "11111",
//     'breadcrumb'=> ['<a href="/sim-ngu-quy">Sim Ngũ Quý</a>']
//   ],
//   [
//     'title'=> "Sim Ngũ Quý 2",
//     'name'=> "Sim Ngũ Quý 2",
//     'label'=> "Sim Ngũ Quý 2",
//     'link'=> "/sim-ngu-quy-22222",
//     'catId'=> '99',
//     'tail'=> "22222",
//     'breadcrumb'=> ['<a href="/sim-ngu-quy">Sim Ngũ Quý</a>']
//   ],
//   [
//     'title'=> "Sim Ngũ Quý 3",
//     'name'=> "Sim Ngũ Quý 3",
//     'label'=> "Sim Ngũ Quý 3",
//     'link'=> "/sim-ngu-quy-33333",
//     'catId'=> '99',
//     'tail'=> "33333",
//     'breadcrumb'=> ['<a href="/sim-ngu-quy">Sim Ngũ Quý</a>']
//   ],
//   [
//     'title'=> "Sim Ngũ Quý 4",
//     'name'=> "Sim Ngũ Quý 4",
//     'label'=> "Sim Ngũ Quý 4",
//     'link'=> "/sim-ngu-quy-44444",
//     'catId'=> '99',
//     'tail'=> "44444",
//     'breadcrumb'=> ['<a href="/sim-ngu-quy">Sim Ngũ Quý</a>']
//   ],
//   [
//     'title'=> "Sim Ngũ Quý 5",
//     'name'=> "Sim Ngũ Quý 5",
//     'label'=> "Sim Ngũ Quý 5",
//     'link'=> "/sim-ngu-quy-55555",
//     'catId'=> '99',
//     'tail'=> "55555",
//     'breadcrumb'=> ['<a href="/sim-ngu-quy">Sim Ngũ Quý</a>']
//   ],
//   [
//     'title'=> "Sim Ngũ Quý 6",
//     'name'=> "Sim Ngũ Quý 6",
//     'label'=> "Sim Ngũ Quý 6",
//     'link'=> "/sim-ngu-quy-66666",
//     'catId'=> '99',
//     'tail'=> "66666",
//     'breadcrumb'=> ['<a href="/sim-ngu-quy">Sim Ngũ Quý</a>']
//   ],
//   [
//     'title'=> "Sim Ngũ Quý 7",
//     'name'=> "Sim Ngũ Quý 7",
//     'label'=> "Sim Ngũ Quý 7",
//     'link'=> "/sim-ngu-quy-77777",
//     'catId'=> '99',
//     'tail'=> "77777",
//     'breadcrumb'=> ['<a href="/sim-ngu-quy">Sim Ngũ Quý</a>']
//   ],
//   [
//     'title'=> "Sim Ngũ Quý 8",
//     'name'=> "Sim Ngũ Quý 8",
//     'label'=> "Sim Ngũ Quý 8",
//     'link'=> "/sim-ngu-quy-88888",
//     'catId'=> '99',
//     'tail'=> "88888",
//     'breadcrumb'=> ['<a href="/sim-ngu-quy">Sim Ngũ Quý</a>']
//   ],
//   [
//     'title'=> "Sim Ngũ Quý 9",
//     'name'=> "Sim Ngũ Quý 9",
//     'label'=> "Sim Ngũ Quý 9",
//     'link'=> "/sim-ngu-quy-99999",
//     'catId'=> '99',
//     'tail'=> "99999",
//     'breadcrumb'=> ['<a href="/sim-ngu-quy">Sim Ngũ Quý</a>']
//   ],
//   [
//     'title'=> "Sim Đầu Số ",
//     'name'=> "Sim Đầu Số ",
//     'label'=> "Sim Đầu Số",
//     'link'=> "/sim-dau-so",
//   ],
//   [
//     'title'=> "Sim Số Đẹp ",
//     'name'=> "Sim Số Đẹp",
//     'label'=> "Sim Số Đẹp",
//     'link'=> "/sim-so-dep",
//   ],
//   [
//     'id'=> 61,
//     'catId'=> 77,
//     'title_seo'=> "Sim Năm Sinh",
//     'title'=> "Sim Năm Sinh",
//     'name'=> "Sim Năm Sinh",
//     'label'=> "Sim Năm Sinh",
//     'link'=> "/sim-nam-sinh",
//     'notFilterItem'=> ['category'],
//   ],
//   [
//     'lte'=> 3000000,
//     'link'=> `/sim-gia-re`,
//     'title_seo'=> "Sim Giá Rẻ",
//     'title'=> "Sim Giá Rẻ",
//     'name'=> "Sim Giá Rẻ",
//     'label'=> "Sim Giá Rẻ",
//     'id'=> 62,
//   ],
//   [
//     'id'=> 63,
//     'title_seo'=> "Sim Trả Góp",
//     'title'=> "Sim Trả Góp",
//     'name'=> "Sim Trả Góp",
//     'label'=> "Sim Trả Góp",
//     'store'=> "4166,2383",
//     'link'=> "/sim-tra-gop",
//   ],
//   [
//     'id'=> 64,
//     'title_seo'=> "Sim Trả Góp Viettel",
//     'title'=> "Sim Trả Góp Viettel",
//     'name'=> "Sim Trả Góp Viettel",
//     'label'=> "Sim Trả Góp Viettel",
//     't'=> "1",
//     'store'=> "4166,2383",
//     'link'=> "/sim-tra-gop-viettel",
//     'breadcrumb'=> ['<a href="/sim-tra-gop">Sim Trả Góp</a>']
//   ],
//   [
//     'id'=> 65,
//     'title_seo'=> "Sim Trả Góp Vinaphone",
//     'title'=> "Sim Trả Góp Vinaphone",
//     'name'=> "Sim Trả Góp Vinaphone",
//     'label'=> "Sim Trả Góp Vinaphone",
//     't'=> "2",
//     'store'=> "4166,2383",
//     'link'=> "/sim-tra-gop-vinaphone",
//     'breadcrumb'=> ['<a href="/sim-tra-gop">Sim Trả Góp</a>']
//   ],
//   [
//     'id'=> 66,
//     'title_seo'=> "Sim Trả Góp Mobifone",
//     'title'=> "Sim Trả Góp Mobifone",
//     'name'=> "Sim Trả Góp Mobifone",
//     'label'=> "Sim Trả Góp Mobifone",
//     't'=> "3",
//     'store'=> "4166,2383",
//     'link'=> "/sim-tra-gop-mobifone",
//     'breadcrumb'=> ['<a href="/sim-tra-gop">Sim Trả Góp</a>']
//   ],
//   [
//     'id'=> 67,
//     'title_seo'=> "Sim Trả Góp Vietnamobile",
//     'title'=> "Sim Trả Góp Vietnamobile",
//     'name'=> "Sim Trả Góp Vietnamobile",
//     'label'=> "Sim Trả Góp Vietnamobile",
//     't'=> "4",
//     'store'=> "4166,2383",
//     'link'=> "/sim-tra-gop-vietnamobile",
//     'breadcrumb'=> ['<a href="/sim-tra-gop">Sim Trả Góp</a>']
//   ],
//   // [
//   //   'id'=> 68,
//   //   'title_seo'=> "Sim Trả Góp Gmobile",
//   //   'title'=> "Sim Trả Góp Gmobile",
//   //   'name'=> "Sim Trả Góp Gmobile",
//   //   'label'=> "Sim Trả Góp Gmobile",
//   //   't'=> "5",
//   //   'store'=> "4166,2383",
//   //   'link'=> "/sim-tra-gop-gmobile",
//   //   'breadcrumb'=> ['<a href="/sim-tra-gop">Sim Trả Góp</a>']
//   // ],
//   [
//     'id'=> 69,
//     'title_seo'=> "Sim Trả Góp Itelecom",
//     'title'=> "Sim Trả Góp Itelecom",
//     'name'=> "Sim Trả Góp Itelecom",
//     'label'=> "Sim Trả Góp Itelecom",
//     't'=> "8",
//     'store'=> "4166,2383",
//     'link'=> "/sim-tra-gop-itelecom",
//     'breadcrumb'=> ['<a href="/sim-tra-gop">Sim Trả Góp</a>']
//   ],
//   [
//     'id'=> 70,
//     'title_seo'=> "Sim Tứ Quý Giữa",
//     'title'=> "Sim Tứ Quý Giữa",
//     'name'=> "Sim Tứ Quý Giữa",
//     'label'=> "Sim Tứ Quý Giữa",
//     'catId'=> "103",
//     'link'=> "/sim-tu-quy-giua",
//     'notFilterItem'=> ['category'],
//     'breadcrumb'=> ['<a href="/sim-tu-quy">Sim Tứ Quý</a>']
//   ],
// ];

// export const sugestionCondConcat = [
//   [
//     'arr1'=> filterTel,
//     'arr2'=> filterHead,
//     'midTxt'=> " đầu ",
//     'field1'=> "t",
//     'field2'=> "head",
//     'param2'=> "head",
//   ],
//   [
//     'arr1'=> filterTel,
//     'arr2'=> [...filterPrice, ...filterPriceTrending],
//     'midTxt'=> " giá ",
//     'field1'=> "t",
//     'headTxt'=> "Sim ",
//     'field2'=> "prices",
//     'param2'=> "prices",
//   ],
//   [
//     'arr1'=> filterTel,
//     'arr2'=> filterFates,
//     'midTxt'=> " mệnh ",
//     'headTxt'=> "Sim ",
//     'field1'=> "t",
//     'field2'=> "catFate",
//     'param2'=> "catFate",
//   ],
//   [
//     'arr1'=> filterTel,
//     'arr2'=> filterAccordingAge,
//     'midTxt'=> " tuổi ",
//     'headTxt'=> "Sim ",
//     'field1'=> "t",
//     'field2'=> "yearId",
//     'param2'=> "yearCom",
//   ],
//   [
//     'arr1'=> filterTel,
//     'arr2'=> filterCategories,
//     'midTxt'=> " ",
//     'field1'=> "t",
//     'field2'=> "catId",
//     'param2'=> "catId",
//   ],
//   // cat with other
//   [
//     'arr1'=> filterCategories,
//     'arr2'=> filterHead,
//     'midTxt'=> " đầu ",
//     'field1'=> "catId",
//     'field2'=> "head",
//     'param2'=> "head",
//   ],
//   [
//     'arr1'=> filterCategories,
//     'arr2'=> filterFates,
//     'midTxt'=> " mệnh ",
//     'field1'=> "catId",
//     'field2'=> "catFate",
//     'param2'=> "catFate",
//   ],
//   [
//     'arr1'=> filterCategories,
//     'arr2'=> filterAccordingAge,
//     'midTxt'=> " tuổi ",
//     'field1'=> "catId",
//     'field2'=> "yearId",
//     'param2'=> "yearCom",
//   ],
//   [
//     'arr1'=> filterCategories,
//     'arr2'=> [...filterPrice, ...filterPriceTrending],
//     'midTxt'=> " giá ",
//     'field1'=> "catId",
//     'field2'=> "prices",
//     'param2'=> "prices",
//   ],

//   [
//     'arr1'=> [...filterPrice, ...filterPriceTrending],
//     'arr2'=> filterHead,
//     'midTxt'=> " đầu ",
//     'field1'=> "prices",
//     'field2'=> "head",
//     'param2'=> "head",
//   ],
//   [
//     'arr1'=> [...filterPrice, ...filterPriceTrending],
//     'arr2'=> filterFates,
//     'midTxt'=> " mệnh ",
//     'field1'=> "prices",
//     'field2'=> "catFate",
//     'param2'=> "catFate",
//   ],

//   [
//     'arr1'=> filterHead,
//     'arr2'=> filterFates,
//     'headTxt'=> "Đầu ",
//     'midTxt'=> " mệnh ",
//     'field1'=> "head",
//     'field2'=> "catFate",
//     'param2'=> "catFate",
//   ],
// ];
// export const 'sugestionCondKeyIgnore'=> any[] = [
//   "t7head09", // may ban dau 09
//   "t7head08",
//   "t7head07",
//   "t7head03",
//   "t7head05",
// ];
// export const 'categoryNotDisplayInList'=> any[] = [84, 110, 111, 112, 113, 114];
// export const 'categoryNotDisplayInDetail'=> any[] = [84];

// //* admin
// export const minPriceOptions = [
//   [
//     'label'=> "0",
//     'value'=> "0",
//   ],
//   [
//     'label'=> "500.000",
//     'value'=> "500000",
//   ],
//   [
//     'label'=> "1.000.000",
//     'value'=> "1000000",
//   ],
//   [
//     'label'=> "3.000.000",
//     'value'=> "3000000",
//   ],
//   [
//     'label'=> "5.000.000",
//     'value'=> "5000000",
//   ],
//   [
//     'label'=> "10.000.000",
//     'value'=> "10000000",
//   ],
//   [
//     'label'=> "30.000.000",
//     'value'=> "30000000",
//   ],
//   [
//     'label'=> "50.000.000",
//     'value'=> "50000000",
//   ],
//   [
//     'label'=> "80.000.000",
//     'value'=> "80000000",
//   ],
//   [
//     'label'=> "100.000.000",
//     'value'=> "100000000",
//   ],
//   [
//     'label'=> "150.000.000",
//     'value'=> "150000000",
//   ],
//   [
//     'label'=> "200.000.000",
//     'value'=> "200000000",
//   ],
//   [
//     'label'=> "300.000.000",
//     'value'=> "300000000",
//   ],
//   [
//     'label'=> "500.000.000",
//     'value'=> "500000000",
//   ],
//   [
//     'label'=> "1.000.000.000",
//     'value'=> "1000000000",
//   ],
// ];

// export const maxPriceOptions = [
//   [
//     'label'=> "500.000",
//     'value'=> "500000",
//   ],
//   [
//     'label'=> "1.000.000",
//     'value'=> "1000000",
//   ],
//   [
//     'label'=> "3.000.000",
//     'value'=> "3000000",
//   ],
//   [
//     'label'=> "5.000.000",
//     'value'=> "5000000",
//   ],
//   [
//     'label'=> "10.000.000",
//     'value'=> "10000000",
//   ],
//   [
//     'label'=> "30.000.000",
//     'value'=> "30000000",
//   ],
//   [
//     'label'=> "50.000.000",
//     'value'=> "50000000",
//   ],
//   [
//     'label'=> "80.000.000",
//     'value'=> "80000000",
//   ],
//   [
//     'label'=> "100.000.000",
//     'value'=> "100000000",
//   ],
//   [
//     'label'=> "150.000.000",
//     'value'=> "150000000",
//   ],
//   [
//     'label'=> "200.000.000",
//     'value'=> "200000000",
//   ],
//   [
//     'label'=> "300.000.000",
//     'value'=> "300000000",
//   ],
//   [
//     'label'=> "500.000.000",
//     'value'=> "500000000",
//   ],
//   [
//     'label'=> "1.000.000.000",
//     'value'=> "1000000000",
//   ],
//   [
//     'label'=> "5.000.000.000",
//     'value'=> "5000000000",
//   ],
//   [
//     'label'=> "10.000.000.000",
//     'value'=> "10000000000",
//   ],
//   [
//     'label'=> "15.000.000.000",
//     'value'=> "15000000000",
//   ],
//   [
//     'label'=> "20.000.000.000",
//     'value'=> "20000000000",
//   ],
//   [
//     'label'=> "25.000.000.000",
//     'value'=> "25000000000",
//   ],
//   [
//     'label'=> "30.000.000.000",
//     'value'=> "30000000000",
//   ],
//   [
//     'label'=> "35.000.000.000",
//     'value'=> "35000000000",
//   ],
//   [
//     'label'=> "40.000.000.000",
//     'value'=> "40000000000",
//   ],
//   [
//     'label'=> "45.000.000.000",
//     'value'=> "45000000000",
//   ],
//   [
//     'label'=> "50.000.000.000",
//     'value'=> "50000000000",
//   ],
//   [
//     'label'=> "(không có)",
//     'value'=> "",
//   ]
// ];


// export const telcoIdMappings = [
//   'viettel'=> 1,
//   'vinaphone'=> 2,
//   'mobifone'=> 3,
//   'vietnamobile'=> 4,
//   // 'gmobile'=> 5,
//   'mayban'=> 7,
//   'itelecom'=> 8,
// ];

// export const filterKep = [
//   [
//     'catId'=> "K2",
//     'label'=> "Sim kép 2",
//     'link'=> "/sim-kep-2",
//   ],
//   [
//     'catId'=> "121",
//     'label'=> "Sim kép 3",
//     'link'=> "/sim-kep-3",
//   ],
//   [
//     'catId'=> "122",
//     'label'=> "Sim kép 4",
//     'link'=> "/sim-kep-4",
//   ],
// ];

// export const filterLap = [
//   [
//     'catId'=> "L2",
//     'label'=> "Sim lặp 2",
//     'link'=> "/sim-lap-2",
//   ],
//   [
//     'catId'=> "124",
//     'label'=> "Sim lặp 3",
//     'link'=> "/sim-lap-3",
//   ],
//   [
//     'catId'=> "125",
//     'label'=> "Sim lặp 4",
//     'link'=> "/sim-lap-4",
//   ],
// ];

// export const filterIncreasingTail = [
//   [
//     'link'=> "/sim-tien-3",
//   ],
//   [
//     'link'=> "/sim-tien-4",
//   ],
//   [
//     'link'=> "/sim-tien-5",
//   ],
//   [
//     'link'=> "/sim-tien-doi",
//   ],
// ];

// export const listPresentFilter = [
//   [
//     'id'=> "1",
//     'title'=> "Tiến Lên",
//     'name'=> "Tiến Lên",
//     'label'=> "6789",
//     'catId'=> "81",
//     'link'=> "/sim-tien-len",
//     'showCat'=> ["/sim-tien-3", "/sim-tien-4", "/sim-tien-5"],
//   ],
//   [
//     'id'=> "2",
//     'title'=> "Tam Hoa",
//     'name'=> "Tam Hoa",
//     'label'=> "Sim Tam Hoa",
//     'catId'=> "80",
//     'link'=> "/sim-tam-hoa",
//     'showCat'=> [],
//   ],
//   [
//     'id'=> "3",
//     'name'=> "Lộc Phát",
//     'title'=> "Lộc Phát",
//     'label'=> "Lộc Phát",
//     'link'=> "/sim-loc-phat",
//     'catId'=> "73",
//     'showCat'=> [],
//   ],
//   [
//     'id'=> "4",
//     'title'=> "Lặp Kép",
//     'name'=> "Lặp Kép",
//     'label'=> "AA.BB",
//     'catId'=> "67",
//     'link'=> "/sim-lap-kep",
//     'showCat'=> [
//       "/sim-lap",
//       "/sim-kep",
//       "/sim-kep-2",
//       "/sim-kep-3",
//       "/sim-kep-4",
//       "/sim-lap-2",
//       "/sim-lap-3",
//       "/sim-lap-4",
//     ],
//   ],
//   [
//     'id'=> "5",
//     'title'=> "Thần Tài",
//     'name'=> "Thần Tài",
//     'label'=> "Thần Tài",
//     'catId'=> "72",
//     'link'=> "/sim-than-tai",
//     'showCat'=> [],
//     'notFilterItem'=> ["category"],
//   ],
//   [
//     'id'=> "6",
//     'title'=> "Ông Địa",
//     'name'=> "Ông Địa",
//     'label'=> "Ông Địa",
//     'catId'=> "70",
//     'link'=> "/sim-ong-dia",
//     'showCat'=> [],
//     'notFilterItem'=> ["category"],
//   ],
//   [
//     'id'=> '7',
//     'label'=> "taxi/hotline",
//     'title'=> "Taxi/hotline",
//     'name'=> "Taxi/hotline",
//     'catId'=> "74",
//     'link'=> "/sim-taxi",
//     'showCat'=> ["/sim-taxi-2", "/sim-taxi-3", "/sim-taxi-4"],
//   ],
//   [
//     'id'=> "8",
//     'name'=> "Gánh Đảo",
//     'title'=> "Gánh Đảo",
//     'label'=> "Gánh Đảo",
//     'catId'=> "79",
//     'link'=> "/sim-ganh-dao",
//     'showCat'=> [],
//   ],
//   [
//     'id'=> "9",
//     'name'=> "Năm Sinh",
//     'title'=> "Năm Sinh",
//     'label'=> "Năm Sinh",
//     'link'=> "/sim-nam-sinh",
//     'notFilterItem'=> ['category'],
//     'catId'=> "77",
//   ],
// ];

// export const filterLinkCategories = [
//   [
//     'catId'=> 100,
//     'link'=> "/sim-luc-quy",
//   ],
//   [
//     'catId'=> 99,
//     'link'=> "/sim-ngu-quy",
//   ],
//   [
//     'catId'=> 68,
//     'link'=> "/sim-tu-quy",
//   ],
//   [
//     'catId'=> 102,
//     'link'=> "/sim-tam-hoa-kep",
//   ],
//   [
//     'catId'=> 80,
//     'link'=> "/sim-tam-hoa",
//   ],
// ]
